songslib/catalog/urls.py
from django.urls import path, re_path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    re_path(r'^songs/$', views.SongListView.as_view(), name='songs'),
    re_path(r'^songs/(?P<pk>\d+)$', views.SongDetailView.as_view(), name='song-detail'),
    re_path(r'^singers/$', views.SingerListView.as_view(), name = 'singers'),
    re_path(r'^singers/(?P<pk>\d+)$', views.SingerDetailView.as_view(), name = 'singer-detail'),
]

songslib/songslib/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('catalog/', include('catalog.urls')),
    path('', RedirectView.as_view(url='catalog/')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

songslib/catalog/models.py
from django.db import models
from django.urls import reverse #Used to generate URLs by reversing the URL patterns

# Create your models here.

class Genre(models.Model):
    """
    Model representing a song genre.
    """
    name = models.CharField(max_length=200, help_text="Enter song genre")

    def __str__(self) -> str:
        """
        String for representing the Model object (in Admin site etc.)
        """
        return self.name


class Singer(models.Model):
    """
    Model representing an singer.
    """
    name = models.CharField(max_length=100)
    description = models.TextField(max_length=1000, help_text="Enter a short description")
    

    def get_absolute_url(self):
        """
        Returns the url to access a particular singer instance.
        """
        return reverse('singer-detail', args=[str(self.id)])


    def __str__(self):
        """
        String for representing the Model object.
        """
        return self.name


class Song(models.Model):
    """
    Model representing a song.
    """
    name = models.CharField(max_length=200)
    singer = models.ForeignKey('Singer', on_delete=models.SET_NULL, null=True)
    # Foreign Key used because song can only have one singer, but singers can have multiple songs
    # Singer as a string rather than object because it hasn't been declared yet in the file.
    lyrics = models.TextField(help_text="Enter a song text")
    chords = models.TextField(help_text="Enter the list of chords")
    genre = models.ManyToManyField(Genre, help_text="Select a genre for this song")
    # ManyToManyField used because genre can contain many songs. Songs can cover many genres.
    # Genre class has already been defined so we can specify the object above.

    def __str__(self):
        """
        String for representing the Model object.
        """
        return self.name


    def get_absolute_url(self):
        """
        Returns the url to access a particular song instance.
        """
        return reverse('song-detail', args=[str(self.id)])

    def display_genre(self):
        """
        Creates a string for the Genre. This is required to display genre in Admin.
        """
        return ', '.join([ genre.name for genre in self.genre.all()[:3] ])
    display_genre.short_description = 'Genre'

songslib/catalog/views.py
from django.shortcuts import render
from django.views import generic

# Create your views here.
from .models import Song, Singer

def index(request):
    """
    Функция отображения для домашней страницы сайта.
    """
    # Генерация "количеств" некоторых главных объектов
    num_songs=Song.objects.all().count()
    num_singers=Singer.objects.count()  # Метод 'all()' применён по умолчанию.

    # Number of visits to this view, as counted in the session variable.
    num_visits=request.session.get('num_visits', 0)
    request.session['num_visits'] = num_visits+1

    # Отрисовка HTML-шаблона index.html с данными внутри
    # переменной контекста context
    return render(
        request,
        'index.html',
        context={'num_songs':num_songs,'num_singers':num_singers, 'num_visits':num_visits},
    )

class SongListView(generic.ListView):
    model = Song
    paginate_by = 20

class SongDetailView(generic.DetailView):
    model = Song

    def song_detail_view(request,pk):
        try:
            song_id=Song.objects.get(pk=pk)
        except Song.DoesNotExist:
            raise Http404("Book does not exist")

        #book_id=get_object_or_404(Book, pk=pk)

        return render(
            request,
            'catalog/song_detail.html',
            context={'song':song_id,}
        )

    def chords_view(pk):
        song_id=Song.objects.get(pk=pk)
        song_id.lyrics = song_id.lyrics.replace('[', '<span class = "chord">').replace(']', '</span>')
        return song_id.lyrics

class SingerListView(generic.ListView):
    model = Singer

class SingerDetailView(generic.DetailView):
    model = Singer

songslib/catalog/templates/base_generic.html
<!DOCTYPE html>
<html lang="en">
<head>

  {% block title %}<title>Local Library</title>{% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

  <!-- Добавление дополнительного статического CSS файла -->
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>

<body>

  <div class="container-fluid">

    <div class="row">
      <div class="col-sm-2">
      {% block sidebar %}
      <ul class="sidebar-nav">
          <li><a href="{% url 'index' %}">Home</a></li>
          <li><a href="{% url 'songs' %}">All songs</a></li>
          <li><a href="{% url 'singers' %}">All singers</a></li>
      </ul>
    {% endblock %}
        </div>
      <div class="col-sm-10 ">
          {% block content %}{% endblock %}
          {% block pagination %}
          {% if is_paginated %}
          <div class="pagination">
              <span class="page-links">
                  {% if page_obj.has_previous %}
                  <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">previous</a>
                  {% endif %}
                  <span class="page-current">
                      Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                  </span>
                  {% if page_obj.has_next %}
                  <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">next</a>
                  {% endif %}
              </span>
          </div>
          {% endif %}
          {% endblock %}
      </div>
    </div>

  </div>
</body>
</html>

songslib/catalog/templates/catalog/singer_detail.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Singer: {{ singer.name}} </h1>

    <p class = "text-muted" >
    <i>{{ singer.description}}</i>
    </p>
    <hr>
    <div style="margin-left:20px;margin-top:20px">
        
        <h4>SONGS</h4>

        {% for song in singer.song_set.all %}
        <div style="margin-left:20px;margin-top:20px">
            <p><strong><a href="{% url 'song-detail' song.pk %}">{{ song.name }}</a></strong></p>
        </div>
        {% endfor %}
    </div>
{% endblock %}

songslib/catalog/templates/catalog/singer_list.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Singer List</h1>

    {% if singer_list %}
    <ul>

      {% for singer in singer_list %}
      <li>
        <a href="{{ singer.get_absolute_url }}">{{ singer.name }} </a>
      </li>
      {% endfor %}

    </ul>
    {% else %}
      <p>There are no singers.</p>
    {% endif %} 
{% endblock %}

songslib/catalog/templates/catalog/song_detail.html
{% extends "base_generic.html" %}

{% block content %}
<h1>Song: "{{ song.name }}" </h1>

<p><strong>Singer:</strong> <a href="{% url 'singer-detail' song.singer.pk %}">{{ song.singer }}</a></p>
<p><strong>Genre:</strong> {% for genre in song.genre.all %} {{ genre }}{% if not forloop.last %}, {% endif %}{% endfor %}</p>

<div style="margin-left:20px;margin-top:20px">
    <h4>Lyrics</h4>
    <pre>{{ song.lyrics}}</pre>
</div>

<div style="margin-left:20px;margin-top:20px">
    <h4>Chords</h4>
    <pre>{{ song.chords }}</pre>
</div>

{% endblock %}

songslib/catalog/templates/catalog/song_list.html
{% extends "base_generic.html" %}

{% block content %}
<h1>Song List</h1>

    {% if song_list %}
<ul>

    {% for song in song_list %}
    <li>
        <a href="{{ song.get_absolute_url }}">{{ song.name}}</a> (<a href="{% url 'singer-detail' song.singer.pk %}">{{song.singer}}</a>)
    </li>
    {% endfor %}

</ul>
    {% else %}
<p>There are no songs in the library.</p>
    {% endif %}
{% endblock %}

songslib/catalog/templates/index.html
{% extends "base_generic.html" %}

{% block content %}
<h1>Songs Library Home</h1>

  <p>Welcome to <em>SongsLibrary</em></p>

<h2>Dynamic content</h2>

  <p>The library has the following record counts:</p>
  <ul>
    <li><strong>Songs:</strong> {{ num_songs }}</li>
    <li><strong>Singers:</strong> {{ num_singers }}</li>
  </ul>

  <p>You have visited this page {{ num_visits }}{% if num_visits == 1 %} time{% else %} times{% endif %}.</p>

{% endblock %}

songslib/catalog/templates/song_detail.html
{% extends "base_generic.html" %}

{% block content %}
<h1>Song: "{{ song.name }}" </h1>

<p><strong>Singer:</strong> <a href="">{{ song.singer }}</a></p> <!-- author detail link not yet defined -->
<p><strong>Genre:</strong> {% for genre in song.genre.all %} {{ genre }}{% if not forloop.last %}, {% endif %}{% endfor %}</p>

<div style="margin-left:20px;margin-top:20px">
    <h4>Lyrics</h4>
    <pre>{{ song.lyrics}}</pre>
</div>

<div style="margin-left:20px;margin-top:20px">
    <h4>Chords</h4>
    <pre>{{ song.chords }}</pre>
</div>

{% endblock %}

songslib/catalog/templates/song_list.html
{% extends "base_generic.html" %}

{% block content %}
<h1>Song List</h1>

    {% if song_list %}
<ul>

    {% for song in song_list %}
    <li>
        <a href="{{ song.get_absolute_url }}">{{ song.name}}</a> (<a href="">{{song.singer}}</a>)
    </li>
    {% endfor %}

</ul>
    {% else %}
<p>There are no songs in the library.</p>
    {% endif %}
{% endblock %}